<x-guest-layout>
    <x-page-title title="Terms of Service - Libraclass" />
    <div class="section page-banner bg-transparent">
        <div class="container mt-5">
            <div class="page-banner-content py-5">
                <ul class="breadcrumb mt-5">
                    <li><a href="/">Home</a></li>
                    <li class="active">Terms and Conditions</li>
                </ul>
                <h2 class="title">Terms of Service</h2>
            </div>
        </div>
    </div>

    <!-- FAQ Start -->
    <div class="section section-padding pt-0">
        <div class="container">
            <p>1. <strong>Introduction</strong></p>
            <p>Welcome to <a href="/">www.libraclass.com</a> (&ldquo;Company&rdquo;, &ldquo;we&rdquo;, &ldquo;our&rdquo;, &ldquo;us&rdquo;)!</p>
            <p>These Terms of Service (&ldquo;Terms&rdquo;, &ldquo;Terms of Service&rdquo;) govern your use of our website located at <strong>libraclass.com</strong> (together or individually &ldquo;Service&rdquo;) operated by <strong>www.libraclass.com</strong>.</p>
            <p>Our Privacy Policy also governs your use of our Service and explains how we collect, safeguard and disclose information that results from your use of our web pages.</p>
            <p>Your agreement with us includes these Terms and our Privacy Policy (&ldquo;Agreements&rdquo;). You acknowledge that you have read and understood Agreements, and agree to be bound by them.</p>
            <p>If you do not agree with (or cannot comply with) Agreements, then you may not use the Service, but please let us know by emailing at <strong>support@libraclass.com</strong> so we can try to find a solution. These Terms apply to all visitors, users and others who wish to access or use Service.</p>
            <p><strong>2. Making Use of Libraclass</strong></p>
            <p>You acknowledge and agree that Libraclass and the Libraclass platform are private communities, and Libraclass reserves the right, in its sole discretion, to provide or refuse service to any user, or to accept or reject student on any basis.</p>
            <p>a. <strong>Become a Student</strong></p>
            <p>Subject to these terms and conditions, anyone may generally purchase products from Libraclass. Purchases will require valid email addresses and phone numbers. Libraclass reserves the right to deny service to anyone who, in Libraclass's sole discretion, seeks refunds without justification or on a regular basis ("serial refunders"). Buyers who repeatedly or consistently seek refunds on a large number of products purchased, particularly when those products have been reviewed and received favorable ratings, may be labelled as serial refunders and denied further service. Any outstanding refunds will be issued, and service will be denied to the account holder thereafter.</p>
            <p>Furthermore, Libraclass makes it simple to request refunds within the money-back window for the purchased product. If a buyer refuses to follow Libraclass's approved refund procedures and the agreed-upon refund period, Libraclass reserves the right to bar the buyer from using Libraclass or the Libraclass platform as a buyer, mentor, or affiliate in the future, and such failure to comply shall be treated as waiver. If a product is not covered by a money-back guarantee, Libraclass will notify the potential buyer by posting a message on the product's sales/order page.</p>
            <p>3. <strong>Mentors: Product/Content Sale</strong></p>
            <p>Content: As a mentor, you may upload one or more courses for sale ("products") on the Libraclass learning platform using your Mentor ID. The products may include any type of course in fields that border on Personal Development, Information Technology, Computer Science, Web Development, Business, Social Science etc.</p>
            <p>Libraclass does not act as a reseller for the mentors' products, but rather provides a learning feature with a slew of sale engineering features. This means that buyers are purchasing directly from the mentor rather than Libraclass. Except as otherwise provided herein, you retain all rights and liabilities to your products.</p>
            <p>It is in your best interests to ensure the quality of your product (s). Each product will be subject to customer reviews and/or ratings, which will be available and/or prominently displayed to potential buyers of your product(s) in the market.</p>
            <p>&nbsp;(i) <strong>Allowed product(s)/content(s):</strong></p>
            <p>Libraclass does not permit, and you agree not to submit, any product(s) or content that are pornographic or offensive in nature, or that relate to pyramid schemes, multi-level marketing (mlm), or any illegal activity, or that contain any illegal material, including but not limited to material that violates another's copyrights or trademarks, trade dress, trade secrets, right of publicity, privacy, or other rights, including moral rights or rights of attribution.</p>
            <p>(ii) <strong>Pricing of Product(s)/Content(s):</strong></p>
            <p>Only mentors may set the price ("sales price") of their own courses within Libraclass's minimum and/or maximum price limits ("price limits"). As a mentor, you agree not to price any product submitted to the platform above the current price limits in effect at the time of submission to the Libraclass platform. Libraclass will prominently display its current price limits on the website. For any product offered for sale in the platform, the "lower price limit" is currently $10 and the "upper price limit" is $500.</p>
            <p>As a mentor, you understand and agree not to sell the same product listed on the Libraclass platform at a higher price elsewhere. Your website is included in this. When a mentor changes the price of a specific product listed on the Libraclass platform on the mentor's website, the mentor must notify Libraclass in order for the price to be updated on the Libraclass website as well.</p>
            <p>Libraclass reserves the right to suspend a Mentor's product if the price listed on the Mentor's website differs from the price listed on Libraclass.</p>
            <p>Libraclass may terminate any mentor who repeatedly violates this provision, and the mentor is solely responsible for any liability that may result.</p>
            <p>The products must be original, and the mentor must have all necessary copyrights to the product(s) and content in order for Libraclass to sell it (s). The product(s) must not fall into any of our prohibited niches (pornography, gambling, pyramid schemes, etc).</p>
            <p><strong>Mentors warrant and represent that;&nbsp;</strong></p>
            <p>They have the full authority and right to enter into this Agreement with Libraclass.</p>
            <p>All of their obligations under this Agreement are legal, valid, and legally binding obligations.</p>
            <p>There are no pending proceedings that may have a material adverse effect on their ability to perform and meet their obligations under this Agreement; that they are an authorized business establishment and have all of the necessary permissions, authorities, approvals, and sanctions to conduct business and enter into an agreement with the Libraclass.</p>
            <p>There are no pending proceedings that could have a materially negative impact.</p>
            <p>They shall at all times ensure compliance with all requirements applicable to their business and for the purposes of this agreement, including but not limited to Intellectual Property Rights, Trade Marks, and any other third party, and that they have not violated/infringed any third party's intellectual property rights.</p>
            <p>That they will provide Libraclass with copies of any documents required by Libraclass for the performance of its obligations under this agreement within 24 hours of receiving written notice.</p>
            <p>That complete product responsibility and liability shall solely vest with Mentor, and that Mentor shall be solely responsible to the customer for the sale of the Product by Mentor, including but not limited to its delivery to the Customer, and that Mentor shall make no claim on Libraclass in this regard.</p>
            <p>Mentor agrees and undertakes not to upload any text, images, or graphics (for product descriptions and display on the online store) that are vulgar, obnoxious, inaccurate, false, incorrect, misleading, intimidating, or violate public policy.</p>
            <p>The Mentor indemnifies and shall hold Libraclass, its directors, officers, employees, representatives, and agents harmless from and against all losses, damages, claims, suits, legal proceedings, and other liabilities arising from or in connection with any claim, including but not limited to claims for infringement of any intellectual property rights or other rights of any third party or of law, concerning quality, quantity, and any claim relating to the Mentor's product.</p>
            <p>Libraclass shall include the Mobile Operators and any other agencies through which Libraclass makes the Online Store available to the Customers for the purposes of this article.</p>
            <p>The Company agrees to indemnify and hold the Mentor harmless from all claims, losses, and expenditures (including, if applicable, litigation costs) arising from Libraclass's failure to perform its duties under this Agreement.</p>
            <p>This article will remain in effect even if the Agreement is terminated or expires.</p>
            <p>Libraclass shall not be liable or responsible for any loss, injury, or damage to the Mentor or any other party arising out of any transaction under this Agreement or as a result of the Products being in any way defective, unfit, or infringing/violating any third-party laws, regulations, or intellectual property rights.</p>
            <p>Mentor agrees and acknowledges that Mentor is solely responsible for any claims, damages, or allegations arising out of the Products offered for sale through Libraclass online store (including, but not limited to, quality, quantity, price, merchantability, use for a specific purpose, or any other related claim), and that Mentor will hold the Company harmless and indemnified against all such claims and damages.</p>
            <p>Furthermore, Libraclass will not be liable for any claims or damages stemming from the Mentor's or any of its representatives' carelessness, misconduct, or misrepresentation.</p>
            <p>The Mentor agrees, confirms, and acknowledges that the Product is owned by the Mentor and that Libraclass is merely a facilitator for the sale of the Mentor's Product; as a result, Libraclass is not responsible/ liable for the Product, its design, function, and condition, manufacturing and selling, financial obligations, warranties, or guarantees of any kind.</p>
            <p>4. <strong>Affiliates: Promoting Products/Courses For A Commission</strong>As a Libraclass platform affiliate, you'll be able to promote and earn money on a wide range of courses available through the cutting-edge Libraclass platform, as well as through the referral program. Products sold in the Libraclass platform are given by our sellers for sale by Libraclass, as described above.</p>
            <p>You assess and select the product(s) to promote:</p>
            <p>You are completely responsible for analyzing and selecting the suppliers and product(s) you want to market or advertise as an affiliate. Through its unique review system, Libraclass strives to maintain the greatest level of quality in the platform. Unlike other platforms, where things aren't reviewed and are left to guesswork, here, products are reviewed.</p>
            <p>However, you should be aware that Libraclass is only responsible for ensuring that recommended users earn sufficient commissions and is not responsible for the contents, accuracy, quality, usefulness, or any other features of any product or additional products.</p>
            <p>You understand and agree that regardless of whether your marketing or advertising efforts result in sales or not, you are solely responsible for any costs connected with marketing, advertising, or mailing, including any marketing materials you choose to generate. Libraclass also does not provide legal advice or review of your advertisements, and you are completely responsible for the content of your marketing and advertising activities, as well as any liability that may arise as a result of them.</p>
            <p>You acknowledge and agree that you will not use your marketing and advertising to customize or suggest that you are the seller of the product you are promoting. If you are caught misrepresenting yourself by using the mentor's name(s) as your own, Libraclass may terminate your affiliate account and seize any commissions you have in your affiliate balance without warning.</p>
            <p>Libraclass does not allow, and you agree not to, promote, market, or advertise any items or use pornographic advertisements, pyramid schemes, or multi-level marketing (mlm). You may not advertise products on the Libraclass platform alongside non-permitted products (including products not on the Libraclass platform).</p>
            <p>Libraclass retains the right to choose who receives an affiliate commission for each given sale. Libraclass also retains the right to fire any affiliate who, in Libraclass' exclusive discretion, has manipulated the monitoring of transactions or commissions in an unacceptable manner.</p>
            <p>5. <strong>Amount of product sales commission to be paid:</strong></p>
            <p>Affiliates will receive a compensation defined as a percentage of the sales price of any product ("affiliate commission") for sales arising from those marketing and advertising efforts in exchange for their efforts in marketing and promoting products accessible in the Libraclass platform.</p>
            <p>The affiliate commission for any product(s) can be set anywhere from 5% and 95% by the mentor. Each product's proceeds will be distributed as follows: Libraclass fees will be removed from the gross sales price, and affiliate commissions will be calculated based on the same. After Libraclass fees and affiliate commissions have been paid, the remaining balance will be paid to the product provider.</p>
            <p>6. <strong>Communications</strong></p>
            <p>By using our Service, you agree to subscribe to newsletters, marketing or promotional materials and other information we may send. However, you may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or by emailing at support@libraclass.com.</p>
            <p>7. <strong>Purchases</strong></p>
            <p>If you wish to purchase any course made available through Service (&ldquo;Purchase&rdquo;), you may be asked to supply certain information relevant to your Purchase including but not limited to, your credit or debit card number, the expiration date of your card, your billing address, and your personal details.</p>
            <p>You represent and warrant that: (i) you have the legal right to use any card(s) or other payment method(s) in connection with any Purchase; and that (ii) the information you supply to us is true, correct and complete.</p>
            <p>We may employ the use of third party services for the purpose of facilitating payment and the completion of Purchases. By submitting your information, you grant us the right to provide the information to these third parties subject to our Privacy Policy.</p>
            <p>We reserve the right to refuse or cancel your order at any time for reasons including but not limited to: product or service availability, errors in the description or price of the product or service, error in your order or other reasons.</p>
            <p>We reserve the right to refuse or cancel your order if fraud or an unauthorised or illegal transaction is suspected.</p>
            <p>8. <strong>Promotions/Referral Program</strong></p>
            <p>Any contests, sweepstakes or other promotions (collectively, &ldquo;Promotions&rdquo;) made available through Service may be governed by rules that are separate from these Terms of Service. If you participate in any Promotions, please review the applicable rules as well as our Privacy Policy. If the rules for a Promotion conflict with these Terms of Service, Promotion rules will apply.</p>
            <p>9. <strong>Refunds</strong></p>
            <p>We issue refunds for Contracts within <strong>30 days</strong> of the original purchase of the Contract.</p>
            <p>10. <strong>Content</strong></p>
            <p>Our Service allows you to post, link, store, share and otherwise make available certain information, text, graphics, videos, or other material (&ldquo;Content&rdquo;). You are responsible for Content that you post on or through Service, including its legality, reliability, and appropriateness.</p>
            <p>By posting Content on or through Service, You represent and warrant that: (i) Content is yours (you own it) and/or you have the right to use it and the right to grant us the rights and licence as provided in these Terms, and (ii) that the posting of your Content on or through Service does not violate the privacy rights, publicity rights, copyrights, contract rights or any other rights of any person or entity. We reserve the right to terminate the account of anyone found to be infringing on a copyright.</p>
            <p>You retain any and all of your rights to any Content you submit, post or display on or through Service and you are responsible for protecting those rights. We take no responsibility and assume no liability for Content you or any third party posts on or through Service. However, by posting Content using Service you grant us the right and licence to use, modify, publicly perform, publicly display, reproduce, and distribute such Content on and through Service. You agree that this licence includes the right for us to make your Content available to other users of Service, who may also use your Content subject to these Terms.</p>
            <p>www.libraclass.com has the right but not the obligation to monitor and edit all Content provided by users.</p>
            <p>In addition, Content found on or through this Service are the property of www.libraclass.com or used with permission. You may not distribute, modify, transmit, reuse, download, repost, copy, or use said Content, whether in whole or in part, for commercial purposes or for personal gain, without express advance written permission from us.</p>
            <p>11. <strong>Prohibited Uses</strong></p>
            <p>You may use Service only for lawful purposes and in accordance with Terms. You agree not to use Service:</p>
            <ul>
            <li>In any way that violates any applicable national or international law or regulation.</li>
            <li>For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way by exposing them to inappropriate content or otherwise.</li>
            <li>To transmit, or procure the sending of, any advertising or promotional material, including any &ldquo;junk mail&rdquo;, &ldquo;chain letter,&rdquo; &ldquo;spam,&rdquo; or any other similar solicitation.</li>
            <li>To impersonate or attempt to impersonate Company, a Company employee, another user, or any other person or entity.</li>
            <li>In any way that infringes upon the rights of others, or in any way is illegal, threatening, fraudulent, or harmful, or in connection with any unlawful, illegal, fraudulent, or harmful purpose or activity.</li>
            <li>To engage in any other conduct that restricts or inhibits anyone&rsquo;s use or enjoyment of Service, or which, as determined by us, may harm or offend Company or users of Service or expose them to liability.</li>
            </ul>
            <p>Additionally, you agree not to:</p>
            <ul>
            <li>Use Service in any manner that could disable, overburden, damage, or impair Service or interfere with any other party&rsquo;s use of Service, including their ability to engage in real time activities through Service.</li>
            <li>Use any robot, spider, or other automatic device, process, or means to access Service for any purpose, including monitoring or copying any of the material on Service.</li>
            <li>Use any manual process to monitor or copy any of the material on Service or for any other unauthorised purpose without our prior written consent.</li>
            <li>Use any device, software, or routine that interferes with the proper working of Service.</li>
            <li>Introduce any viruses, trojan horses, worms, logic bombs, or other material which is malicious or technologically harmful.</li>
            <li>Attempt to gain unauthorised access to, interfere with, damage, or disrupt any parts of Service, the server on which Service is stored, or any server, computer, or database connected to Service.</li>
            <li>Attack Service via a denial-of-service attack or a distributed denial-of-service attack.</li>
            <li>Take any action that may damage or falsify Company ratings.</li>
            <li>Otherwise attempt to interfere with the proper working of Service.</li>
            </ul>
            <p>12. <strong>Analytics</strong></p>
            <p>We may use third-party Service Providers to monitor and analyse the use of our Service.</p>
            <p>13. <strong>Accounts</strong></p>
            <p>When you create an account with us, you guarantee that the information you provide us is accurate, complete, and current at all times. Inaccurate, incomplete, or obsolete information may result in the immediate termination of your account on Service.</p>
            <p>You are responsible for maintaining the confidentiality of your account and password, including but not limited to the restriction of access to your computer and/or account. You agree to accept responsibility for any and all activities or actions that occur under your account and/or password, whether your password is with our Service or a third-party service. You must notify us immediately upon becoming aware of any breach of security or unauthorised use of your account.</p>
            <p>You may not use as a username the name of another person or entity or that is not lawfully available for use, a name or trademark that is subject to any rights of another person or entity other than you, without appropriate authorization. You may not use as a username any name that is offensive, vulgar or obscene.</p>
            <p>We reserve the right to refuse service, terminate accounts, remove or edit content, or cancel orders at our sole discretion.</p>
            <p>14. <strong>Intellectual Property</strong></p>
            <p>Service and its original content (excluding Content provided by users), features and functionality are and will remain the exclusive property of www.libraclass.com and its licensors. Service is protected by copyright, trademark, and other laws of and foreign countries. Our trademarks may not be used in connection with any product or service without the prior written consent of www.libraclass.com.</p>
            <p>15. <strong>Copyright Policy</strong></p>
            <p>We respect the intellectual property rights of others. It is our policy to respond to any claim that Content posted on Service infringes on the copyright or other intellectual property rights (&ldquo;Infringement&rdquo;) of any person or entity.</p>
            <p>If you are a copyright owner, or authorised on behalf of one, and you believe that the copyrighted work has been copied in a way that constitutes copyright infringement, please submit your claim via email to support@libraclass.com, with the subject line: &ldquo;Copyright Infringement&rdquo; and include in your claim a detailed description of the alleged Infringement as detailed below, under &ldquo;DMCA Notice and Procedure for Copyright Infringement Claims&rdquo;</p>
            <p>You may be held accountable for damages (including costs and attorneys&rsquo; fees) for misrepresentation or bad-faith claims on the infringement of any Content found on and/or through Service on your copyright.</p>
            <p>16. <strong>DMCA Notice and Procedure for Copyright Infringement Claims</strong></p>
            <p>You may submit a notification pursuant to the Digital Millennium Copyright Act (DMCA) by providing our Copyright Agent with the following information in writing (see 17 U.S.C 512(c)(3) for further detail):</p>
            <ul>
            <li>an electronic or physical signature of the person authorised to act on behalf of the owner of the copyright&rsquo;s interest;</li>
            <li>a description of the copyrighted work that you claim has been infringed, including the URL (i.e., web page address) of the location where the copyrighted work exists or a copy of the copyrighted work;</li>
            <li>identification of the URL or other specific location on Service where the material that you claim is infringing is located;</li>
            <li>your address, telephone number, and email address;</li>
            <li>a statement by you that you have a good faith belief that the disputed use is not authorised by the copyright owner, its agent, or the law;</li>
            <li>a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorised to act on the copyright owner&rsquo;s behalf.</li>
            </ul>
            <p>You can contact our Copyright Agent via email at support@libraclass.com.</p>
            <p>17. <strong>Error Reporting and Feedback</strong></p>
            <p>You may provide us either directly at support@libraclass.com or via third party sites and tools with information and feedback concerning errors, suggestions for improvements, ideas, problems, complaints, and other matters related to our Service (&ldquo;Feedback&rdquo;). You acknowledge and agree that: (i) you shall not retain, acquire or assert any intellectual property right or other right, title or interest in or to the Feedback; (ii) Company may have development ideas similar to the Feedback; (iii) Feedback does not contain confidential information or proprietary information from you or any third party; and (iv) Company is not under any obligation of confidentiality with respect to the Feedback. In the event the transfer of the ownership to the Feedback is not possible due to applicable mandatory laws, you grant Company and its affiliates an exclusive, transferable, irrevocable, free-of-charge, sub-licensable, unlimited and perpetual right to use (including copy, modify, create derivative works, publish, distribute and commercialise) Feedback in any manner and for any purpose.</p>
            <p>18. <strong>Links To Other Websites</strong></p>
            <p>Our Service may contain links to third party web sites or services that are not owned or controlled by www.libraclass.com.</p>
            <p>www.libraclass.com has no control over, and assumes no responsibility for the content, privacy policies, or practices of any third party web sites or services. We do not warrant the offerings of any of these entities/individuals or their websites.</p>
            <p>YOU ACKNOWLEDGE AND AGREE THAT COMPANY SHALL NOT BE RESPONSIBLE OR LIABLE, DIRECTLY OR INDIRECTLY, FOR ANY DAMAGE OR LOSS CAUSED OR ALLEGED TO BE CAUSED BY OR IN CONNECTION WITH USE OF OR RELIANCE ON ANY SUCH CONTENT, GOODS OR SERVICES AVAILABLE ON OR THROUGH ANY SUCH THIRD PARTY WEB SITES OR SERVICES.</p>
            <p>WE STRONGLY ADVISE YOU TO READ THE TERMS OF SERVICE AND PRIVACY POLICIES OF ANY THIRD PARTY WEB SITES OR SERVICES THAT YOU VISIT.</p>
            <p>19. <strong>Disclaimer Of Warranty</strong></p>
            <p>THESE SERVICES ARE PROVIDED BY COMPANY ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS. COMPANY MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THEIR SERVICES, OR THE INFORMATION, CONTENT OR MATERIALS INCLUDED THEREIN. YOU EXPRESSLY AGREE THAT YOUR USE OF THESE SERVICES, THEIR CONTENT, AND ANY SERVICES OR ITEMS OBTAINED FROM US IS AT YOUR SOLE RISK.</p>
            <p>NEITHER COMPANY NOR ANY PERSON ASSOCIATED WITH COMPANY MAKES ANY WARRANTY OR REPRESENTATION WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, QUALITY, ACCURACY, OR AVAILABILITY OF THE SERVICES. WITHOUT LIMITING THE FOREGOING, NEITHER COMPANY NOR ANYONE ASSOCIATED WITH COMPANY REPRESENTS OR WARRANTS THAT THE SERVICES, THEIR CONTENT, OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE SERVICES WILL BE ACCURATE, RELIABLE, ERROR-FREE, OR UNINTERRUPTED, THAT DEFECTS WILL BE CORRECTED, THAT THE SERVICES OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS OR THAT THE SERVICES OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE SERVICES WILL OTHERWISE MEET YOUR NEEDS OR EXPECTATIONS.</p>
            <p>COMPANY HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, AND FITNESS FOR PARTICULAR PURPOSE.</p>
            <p>THE FOREGOING DOES NOT AFFECT ANY WARRANTIES WHICH CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.</p>
            <p>20. <strong>Limitation Of Liability</strong></p>
            <p>EXCEPT AS PROHIBITED BY LAW, YOU WILL HOLD US AND OUR OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS HARMLESS FOR ANY INDIRECT, PUNITIVE, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGE, HOWEVER IT ARISES (INCLUDING ATTORNEYS&rsquo; FEES AND ALL RELATED COSTS AND EXPENSES OF LITIGATION AND ARBITRATION, OR AT TRIAL OR ON APPEAL, IF ANY, WHETHER OR NOT LITIGATION OR ARBITRATION IS INSTITUTED), WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE, OR OTHER TORTIOUS ACTION, OR ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT, INCLUDING WITHOUT LIMITATION ANY CLAIM FOR PERSONAL INJURY OR PROPERTY DAMAGE, ARISING FROM THIS AGREEMENT AND ANY VIOLATION BY YOU OF ANY FEDERAL, STATE, OR LOCAL LAWS, STATUTES, RULES, OR REGULATIONS, EVEN IF COMPANY HAS BEEN PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. EXCEPT AS PROHIBITED BY LAW, IF THERE IS LIABILITY FOUND ON THE PART OF COMPANY, IT WILL BE LIMITED TO THE AMOUNT PAID FOR THE PRODUCTS AND/OR SERVICES, AND UNDER NO CIRCUMSTANCES WILL THERE BE CONSEQUENTIAL OR PUNITIVE DAMAGES. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF PUNITIVE, INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE PRIOR LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU.</p>
            <p>21. <strong>Termination</strong></p>
            <p>We may terminate or suspend your account and bar access to Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of Terms.</p>
            <p>If you wish to terminate your account, you may simply discontinue using Service.</p>
            <p>All provisions of Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>

            <p>22. <strong>Governing Law</strong></p>
            <p>These Terms shall be governed and construed in accordance with the laws of the United States of America, which governing law applies to agreement without regard to its conflict of law provisions.</p>
            <p>Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service and supersede and replace any prior agreements we might have had between us regarding Service.</p>
            <p>23. <strong>Changes To Service</strong></p>
            <p>We reserve the right to withdraw or amend our Service, and any service or material we provide via Service, in our sole discretion without notice. We will not be liable if for any reason all or any part of Service is unavailable at any time or for any period. From time to time, we may restrict access to some parts of Service, or the entire Service, to users, including registered users.</p>
            <p>24. <strong>Amendments To Terms</strong></p>
            <p>We may amend Terms at any time by posting the amended terms on this site. It is your responsibility to review these Terms periodically.</p>
            <p>Your continued use of the Platform following the posting of revised Terms means that you accept and agree to the changes. You are expected to check this page frequently so you are aware of any changes, as they are binding on you.</p>
            <p>By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorised to use Service.</p>
            <p>25. <strong>Waiver And Severability</strong></p>
            <p>No waiver by Company of any term or condition set forth in Terms shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of Company to assert a right or provision under Terms shall not constitute a waiver of such right or provision.</p>
            <p>If any provision of Terms is held by a court or other tribunal of competent jurisdiction to be invalid, illegal or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of Terms will continue in full force and effect.</p>
            <p>26. <strong>Acknowledgement</strong></p>
            <p>BY USING SERVICE OR OTHER SERVICES PROVIDED BY US, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS OF SERVICE AND AGREE TO BE BOUND BY THEM.</p>
            <p>27. <strong>Contact Us</strong></p>
            <p>Please send your feedback, comments, requests for technical support by email: <a href="mailto:support@libraclass.com">support@libraclass.com</a>.</p>
        </div>
    </div>
</x-guest-layout>
